# Generated by Django 5.2.1 on 2025-06-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_priotiy_alter_task_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_completed', 'priority_order', '-updated_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='priority_order',
            field=models.IntegerField(default=4, editable=False),
            preserve_default=False,
        ),
    ]
