# Generated by Django 5.2.1 on 2025-06-13 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_options_task_priority_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='priotiy',
            new_name='priority',
        ),
    ]
